[package]
name = "rs-shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2.11"
ntapi = "0.4.1"
signal-hook = "0.3.15"
regex = "1.8.3"
open = "4.1.0"
simple_logger = "4.1.0"
log = "0.4.18"
ctrlc = "3.4.0"

[dependencies.windows-sys]
version = "0.48"
features = [
    "Win32_System_Memory",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_LibraryLoader",
    "Win32_System_Kernel",
]